services:
  postgres:
    image: postgres:15
    container_name: insightly_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: insightly_redis
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"

  llm:
    image: ai/llama3.2
    # image: ollama/ollama
    container_name: insightly_llm
    env_file: .env
    ports:
      - "${LLM_PORT}:11434"
    # Optional: preload models if needed via volumes or ENV

  ingest:
    build:
      context: .
      dockerfile: deployments/ingest.Dockerfile
    container_name: insightly_ingest
    env_file: .env
    ports:
      - "${INGEST_PORT}:50051"
    depends_on:
      - redis

  summarizer:
    build:
      context: .
      dockerfile: deployments/summarizer.Dockerfile
    container_name: insightly_summarizer
    env_file: .env
    depends_on:
      - redis
      - postgres
      - llm

  query:
    build:
      context: .
      dockerfile: deployments/query.Dockerfile
    container_name: insightly_query
    env_file: .env
    ports:
      - "${QUERY_PORT}:50052"
    depends_on:
      - postgres

volumes:
  postgres-data: