services:
  postgres:
    image: postgres:15
    container_name: insightly_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: insightly_redis
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"

  # ingest:
  #   build:
  #     context: .
  #     dockerfile: deployments/ingest.Dockerfile
  #   container_name: insightly_ingest
  #   env_file: .env
  #   ports:
  #     - "${INGEST_PORT}:50051"
  #   depends_on:
  #     - redis

  # query:
  #   build:
  #     context: .
  #     dockerfile: deployments/query.Dockerfile
  #   container_name: insightly_query
  #   env_file: .env
  #   ports:
  #     - "${QUERY_PORT}:50052"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #       restart: true

volumes:
  postgres-data: