// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ingest.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single log entry coming from a service
type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`        // Which service/app (e.g., \"auth-service\")
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // UNIX timestamp (UTC seconds)
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`          // \"INFO\", \"WARN\", \"ERROR\", etc.
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`      // Actual log message text
	Metadata      []byte                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`    // (optional) JSON-encoded map of additional fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_proto_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Simple ack after ingestion
type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_proto_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ingest_proto protoreflect.FileDescriptor

const file_proto_ingest_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ingest.proto\x12\x06ingest\"\x8d\x01\n" +
	"\tLogRecord\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\"%\n" +
	"\tIngestAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2A\n" +
	"\tLogIngest\x124\n" +
	"\n" +
	"StreamLogs\x12\x11.ingest.LogRecord\x1a\x11.ingest.IngestAck(\x01B\x16Z\x14/proto/ingest;ingestb\x06proto3"

var (
	file_proto_ingest_proto_rawDescOnce sync.Once
	file_proto_ingest_proto_rawDescData []byte
)

func file_proto_ingest_proto_rawDescGZIP() []byte {
	file_proto_ingest_proto_rawDescOnce.Do(func() {
		file_proto_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingest_proto_rawDesc), len(file_proto_ingest_proto_rawDesc)))
	})
	return file_proto_ingest_proto_rawDescData
}

var file_proto_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ingest_proto_goTypes = []any{
	(*LogRecord)(nil), // 0: ingest.LogRecord
	(*IngestAck)(nil), // 1: ingest.IngestAck
}
var file_proto_ingest_proto_depIdxs = []int32{
	0, // 0: ingest.LogIngest.StreamLogs:input_type -> ingest.LogRecord
	1, // 1: ingest.LogIngest.StreamLogs:output_type -> ingest.IngestAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ingest_proto_init() }
func file_proto_ingest_proto_init() {
	if File_proto_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingest_proto_rawDesc), len(file_proto_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingest_proto_goTypes,
		DependencyIndexes: file_proto_ingest_proto_depIdxs,
		MessageInfos:      file_proto_ingest_proto_msgTypes,
	}.Build()
	File_proto_ingest_proto = out.File
	file_proto_ingest_proto_goTypes = nil
	file_proto_ingest_proto_depIdxs = nil
}
