// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogQuery_GetSummaries_FullMethodName = "/query.LogQuery/GetSummaries"
)

// LogQueryClient is the client API for LogQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogQueryClient interface {
	// Fetch latest summaries for a given stream
	GetSummaries(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SummaryResp], error)
}

type logQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewLogQueryClient(cc grpc.ClientConnInterface) LogQueryClient {
	return &logQueryClient{cc}
}

func (c *logQueryClient) GetSummaries(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SummaryResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogQuery_ServiceDesc.Streams[0], LogQuery_GetSummaries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetReq, SummaryResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogQuery_GetSummariesClient = grpc.ServerStreamingClient[SummaryResp]

// LogQueryServer is the server API for LogQuery service.
// All implementations must embed UnimplementedLogQueryServer
// for forward compatibility.
type LogQueryServer interface {
	// Fetch latest summaries for a given stream
	GetSummaries(*GetReq, grpc.ServerStreamingServer[SummaryResp]) error
	mustEmbedUnimplementedLogQueryServer()
}

// UnimplementedLogQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogQueryServer struct{}

func (UnimplementedLogQueryServer) GetSummaries(*GetReq, grpc.ServerStreamingServer[SummaryResp]) error {
	return status.Errorf(codes.Unimplemented, "method GetSummaries not implemented")
}
func (UnimplementedLogQueryServer) mustEmbedUnimplementedLogQueryServer() {}
func (UnimplementedLogQueryServer) testEmbeddedByValue()                  {}

// UnsafeLogQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogQueryServer will
// result in compilation errors.
type UnsafeLogQueryServer interface {
	mustEmbedUnimplementedLogQueryServer()
}

func RegisterLogQueryServer(s grpc.ServiceRegistrar, srv LogQueryServer) {
	// If the following call pancis, it indicates UnimplementedLogQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogQuery_ServiceDesc, srv)
}

func _LogQuery_GetSummaries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogQueryServer).GetSummaries(m, &grpc.GenericServerStream[GetReq, SummaryResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogQuery_GetSummariesServer = grpc.ServerStreamingServer[SummaryResp]

// LogQuery_ServiceDesc is the grpc.ServiceDesc for LogQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.LogQuery",
	HandlerType: (*LogQueryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSummaries",
			Handler:       _LogQuery_GetSummaries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/query.proto",
}
