// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request parameters for fetching summaries
type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"` // e.g., \"auth-service\"
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // How many summaries to return (default: 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *GetReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Each summarized digest
type SummaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	WindowStart   string                 `protobuf:"bytes,2,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"` // ISO8601 formatted start time
	WindowEnd     string                 `protobuf:"bytes,3,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`       // ISO8601 formatted end time
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                                  // The human-readable summary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResp) Reset() {
	*x = SummaryResp{}
	mi := &file_proto_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResp) ProtoMessage() {}

func (x *SummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResp.ProtoReflect.Descriptor instead.
func (*SummaryResp) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryResp) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SummaryResp) GetWindowStart() string {
	if x != nil {
		return x.WindowStart
	}
	return ""
}

func (x *SummaryResp) GetWindowEnd() string {
	if x != nil {
		return x.WindowEnd
	}
	return ""
}

func (x *SummaryResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_query_proto protoreflect.FileDescriptor

const file_proto_query_proto_rawDesc = "" +
	"\n" +
	"\x11proto/query.proto\x12\x05query\"6\n" +
	"\x06GetReq\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"{\n" +
	"\vSummaryResp\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12!\n" +
	"\fwindow_start\x18\x02 \x01(\tR\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x03 \x01(\tR\twindowEnd\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text2?\n" +
	"\bLogQuery\x123\n" +
	"\fGetSummaries\x12\r.query.GetReq\x1a\x12.query.SummaryResp0\x01B\x14Z\x12/proto/query;queryb\x06proto3"

var (
	file_proto_query_proto_rawDescOnce sync.Once
	file_proto_query_proto_rawDescData []byte
)

func file_proto_query_proto_rawDescGZIP() []byte {
	file_proto_query_proto_rawDescOnce.Do(func() {
		file_proto_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_query_proto_rawDesc), len(file_proto_query_proto_rawDesc)))
	})
	return file_proto_query_proto_rawDescData
}

var file_proto_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_query_proto_goTypes = []any{
	(*GetReq)(nil),      // 0: query.GetReq
	(*SummaryResp)(nil), // 1: query.SummaryResp
}
var file_proto_query_proto_depIdxs = []int32{
	0, // 0: query.LogQuery.GetSummaries:input_type -> query.GetReq
	1, // 1: query.LogQuery.GetSummaries:output_type -> query.SummaryResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_query_proto_init() }
func file_proto_query_proto_init() {
	if File_proto_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_query_proto_rawDesc), len(file_proto_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_query_proto_goTypes,
		DependencyIndexes: file_proto_query_proto_depIdxs,
		MessageInfos:      file_proto_query_proto_msgTypes,
	}.Build()
	File_proto_query_proto = out.File
	file_proto_query_proto_goTypes = nil
	file_proto_query_proto_depIdxs = nil
}
